[package]
name = "apex_linux_client"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"  # egui + windowing
egui = "0.29"
memmap2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5"
bincode = "1.3"
env_logger = "0.11"
libc = "0.2"
